use_frameworks!

platform :ios, '10.0'

target 'TableViewSections_Example' do
  pod 'TableViewSections', :path => '../'

  target 'TableViewSections_Tests' do
    inherit! :search_paths

    
  end
end
